# Generated by Django 2.1.7 on 2019-03-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAvr',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('avrTemp', models.FloatField(default=0.0)),
                ('avrSnow', models.FloatField(default=0.0)),
            ],
        ),
    ]
